version: '3.8'

networks:
  elpmas:

services:
  nginx:
    build:
      context: .
      dockerfile: ./.docker/nginx.dockerfile
    volumes:
      - ./server:/var/www
      - ./.docker/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 8000:80
    networks:
      - elpmas
    depends_on:
      - php
    
  php:
    build:
      context: .
      dockerfile: ./.docker/php.dockerfile
    volumes: 
      - ./server:/var/www
    networks:
      - elpmas
    depends_on:
      - mysql
      - smtp

  mysql:
    image: mysql
    tty: true
    volumes:
      - ./.docker/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    command: [mysqld, --default-authentication-plugin=mysql_native_password]
    environment:
      MYSQL_DATABASE: elpmas
      MYSQL_USER: elpmas
      MYSQL_PASSWORD: elpmas
      MYSQL_ROOT_PASSWORD: root
    networks:
      - elpmas

  node:
    build:
      context: .
      dockerfile: ./.docker/node.dockerfile
    tty: true
    volumes: 
      - ./server:/var/www/html
    networks:
      - elpmas

  smtp:
    image: rnwood/smtp4dev:linux-amd64-v3
    ports:
      - 1000:80
    networks:
      - elpmas